<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "muntertheme"
 *
 * Auto generated by Extension Builder 2014-08-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
    'title' => 'Munter Theme',
    'description' => 'One Page Theme for TYPO3',
    'category' => 'distribution',
    'version' => '0.0.1',
    'state' => 'alpha',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearcacheonload' => false,
    'author' => 'Mario Kehl',
    'constraints' =>
        array (
            'depends' =>
                array (
                    'extbase' => '',
                    'fluid' => '',
                    'typo3' => '6.2.0-6.2.99',
                    'css_styled_content' => '',
                ),
            'conflicts' =>
                array (
                ),
            'suggests' =>
                array (
                ),
        ),
);
